// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	createCampaign: (name: string) => typedError<CampaignSummary, AppError>(__TAURI_INVOKE("create_campaign", { name })),
	listCampaigns: () => typedError<CampaignSummary[], AppError>(__TAURI_INVOKE("list_campaigns")),
	openCampaign: (id: string) => typedError<CampaignSummary, AppError>(__TAURI_INVOKE("open_campaign", { id })),
	closeCampaign: () => typedError<null, AppError>(__TAURI_INVOKE("close_campaign")),
	getActiveCampaign: () => typedError<{
	id: string,
	name: string,
	path: string,
	meta: { [key in string]: string },
} | null, AppError>(__TAURI_INVOKE("get_active_campaign")),
	createMap: (name: string, width: number, height: number, gridSize: number) => typedError<MapSummary, AppError>(__TAURI_INVOKE("create_map", { name, width, height, gridSize })),
	listMaps: () => typedError<MapSummary[], AppError>(__TAURI_INVOKE("list_maps")),
	getMap: (id: string) => typedError<{
	id: string,
	worldId: string,
	name: string,
	imagePath: string,
	gridSize: number,
	width: number,
	height: number,
	fogData: string | null,
} | null, AppError>(__TAURI_INVOKE("get_map", { id })),
	createToken: (mapId: string, x: number | null, y: number | null, characterId: string | null) => typedError<TokenSummary, AppError>(__TAURI_INVOKE("create_token", { mapId, x, y, characterId })),
	listTokens: (mapId: string) => typedError<TokenSummary[], AppError>(__TAURI_INVOKE("list_tokens", { mapId })),
	moveToken: (tokenId: string, x: number | null, y: number | null) => typedError<TokenSummary, AppError>(__TAURI_INVOKE("move_token", { tokenId, x, y })),
	deleteToken: (tokenId: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_token", { tokenId })),
	assignTokenCharacter: (tokenId: string, characterId: string | null) => typedError<TokenSummary, AppError>(__TAURI_INVOKE("assign_token_character", { tokenId, characterId })),
	createCharacter: (name: string, characterType: string) => typedError<CharacterSummary, AppError>(__TAURI_INVOKE("create_character", { name, characterType })),
	listCharacters: () => typedError<CharacterSummary[], AppError>(__TAURI_INVOKE("list_characters")),
	createJournalEntry: (title: string, folderPath: string) => typedError<JournalEntrySummary, AppError>(__TAURI_INVOKE("create_journal_entry", { title, folderPath })),
	listJournalEntries: () => typedError<JournalEntrySummary[], AppError>(__TAURI_INVOKE("list_journal_entries")),
	getJournalEntry: (id: string) => typedError<{
	id: string,
	title: string,
	contentMarkdown: string,
	folderPath: string,
	isVisibleToPlayers: boolean,
} | null, AppError>(__TAURI_INVOKE("get_journal_entry", { id })),
	updateJournalEntry: (id: string, title: string, contentMarkdown: string, folderPath: string, isVisibleToPlayers: boolean) => typedError<JournalEntryDetail, AppError>(__TAURI_INVOKE("update_journal_entry", { id, title, contentMarkdown, folderPath, isVisibleToPlayers })),
	deleteJournalEntry: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_journal_entry", { id })),
	getCharacter: (id: string) => typedError<{
	id: string,
	name: string,
	type: string,
	dataJson: string,
} | null, AppError>(__TAURI_INVOKE("get_character", { id })),
	updateCharacter: (id: string, name: string, characterType: string, dataJson: string) => typedError<CharacterDetail, AppError>(__TAURI_INVOKE("update_character", { id, name, characterType, dataJson })),
	importMapImage: (mapId: string, sourcePath: string) => typedError<MapSummary, AppError>(__TAURI_INVOKE("import_map_image", { mapId, sourcePath })),
	readCampaignAssetDataUrl: (relativePath: string) => typedError<string, AppError>(__TAURI_INVOKE("read_campaign_asset_data_url", { relativePath })),
	updateMapFog: (mapId: string, fogData: string | null) => typedError<null, AppError>(__TAURI_INVOKE("update_map_fog", { mapId, fogData })),
	listCompendiums: () => typedError<CompendiumSummary[], AppError>(__TAURI_INVOKE("list_compendiums")),
	listCompendiumEntries: (compendiumId: string) => typedError<CompendiumEntrySummary[], AppError>(__TAURI_INVOKE("list_compendium_entries", { compendiumId })),
	createCompendium: (name: string, compendiumType: string) => typedError<CompendiumSummary, AppError>(__TAURI_INVOKE("create_compendium", { name, compendiumType })),
	createCompendiumEntry: (compendiumId: string, entryKey: string, name: string, dataJson: string) => typedError<CompendiumEntrySummary, AppError>(__TAURI_INVOKE("create_compendium_entry", { compendiumId, entryKey, name, dataJson })),
};

/* Types */
export type ActiveCampaign = {
	id: string,
	name: string,
	path: string,
	meta: { [key in string]: string },
};

export type AppError = { kind: "Db"; message: string } | { kind: "Io"; message: string } | { kind: "Validation"; message: string } | { kind: "NotFound" } | { kind: "NoCampaign" };

export type CampaignSummary = {
	id: string,
	name: string,
	fileName: string,
	createdAt: number,
	lastOpenedAt: number | null,
};

export type CharacterDetail = {
	id: string,
	name: string,
	type: string,
	dataJson: string,
};

export type CharacterSummary = {
	id: string,
	name: string,
	type: string,
};

export type CompendiumEntrySummary = {
	id: string,
	compendiumId: string,
	entryKey: string,
	name: string,
	dataJson: string,
};

export type CompendiumSummary = {
	id: string,
	name: string,
	sourcePluginId: string | null,
	type: string,
};

export type JournalEntryDetail = {
	id: string,
	title: string,
	contentMarkdown: string,
	folderPath: string,
	isVisibleToPlayers: boolean,
};

export type JournalEntrySummary = {
	id: string,
	title: string,
	folderPath: string,
	isVisibleToPlayers: boolean,
};

export type MapSummary = {
	id: string,
	worldId: string,
	name: string,
	imagePath: string,
	gridSize: number,
	width: number,
	height: number,
	fogData: string | null,
};

export type TokenSummary = {
	id: string,
	mapId: string,
	characterId: string | null,
	characterName: string | null,
	x: number | null,
	y: number | null,
	rotation: number | null,
	isVisible: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

