// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	createCampaign: (name: string) => typedError<CampaignSummary, AppError>(__TAURI_INVOKE("create_campaign", { name })),
	listCampaigns: () => typedError<CampaignSummary[], AppError>(__TAURI_INVOKE("list_campaigns")),
	openCampaign: (id: string) => typedError<CampaignSummary, AppError>(__TAURI_INVOKE("open_campaign", { id })),
	closeCampaign: () => typedError<null, AppError>(__TAURI_INVOKE("close_campaign")),
	getActiveCampaign: () => typedError<{
	id: string,
	name: string,
	path: string,
	meta: { [key in string]: string },
} | null, AppError>(__TAURI_INVOKE("get_active_campaign")),
	createMap: (name: string, width: number, height: number, gridSize: number) => typedError<MapSummary, AppError>(__TAURI_INVOKE("create_map", { name, width, height, gridSize })),
	listMaps: () => typedError<MapSummary[], AppError>(__TAURI_INVOKE("list_maps")),
	getMap: (id: string) => typedError<{
	id: string,
	worldId: string,
	name: string,
	imagePath: string,
	gridSize: number,
	width: number,
	height: number,
} | null, AppError>(__TAURI_INVOKE("get_map", { id })),
};

/* Types */
export type ActiveCampaign = {
	id: string,
	name: string,
	path: string,
	meta: { [key in string]: string },
};

export type AppError = { kind: "Db"; message: string } | { kind: "Io"; message: string } | { kind: "Validation"; message: string } | { kind: "NotFound" } | { kind: "NoCampaign" };

export type CampaignSummary = {
	id: string,
	name: string,
	fileName: string,
	createdAt: number,
	lastOpenedAt: number | null,
};

export type MapSummary = {
	id: string,
	worldId: string,
	name: string,
	imagePath: string,
	gridSize: number,
	width: number,
	height: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

